version: 0.1

phases:
  pre_build:
    commands:
      - echo Logging in to Docker...
      - docker login -u $DOCKER_DEVELOPER -p $DOCKER_PASSWORD
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t revenuewire/jenkins-slave:latest .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push revenuewire/jenkins-slave:latest